prometheus: 
  namespace: monitoring
dashboards: 
  mariadb: 
    name: mariadb
    file: mariadb.json
    enable: false
  elasticsearch: 
    name: elasticsearch
    file: elasticsearch.json
    enable: false
  mongodb: 
    name: mongodb
    file: mongodb.json
    enable: false
  postgresqlha: 
    name: postgresqlha
    file: postgresqlha.json
    enable: false
  postgresql: 
    name: postgresql
    file: postgresql.json
    enable: true
  postgresql2: 
    name: postgresql2
    file: postgresql2.json
    enable: true
  postgresql3: 
    name: postgresql3
    file: postgresql3.json
    enable: true
  mariadbgal: 
    name: mariadbgal
    file: mariadbgal.json
    enable: false
  flaskapp:
    name: flaskapp
    file: flaskapp.json
    enable: true
