neo4j:
  image: "neo4j/helm-charts-backup"
  imageTag: "5.12.0"
  jobSchedule: "0 17 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  backoffLimit: 3

backup:
  bucketName: "tec-ic4302-02-2023"
  databaseAdminServiceName:  "databases-admin"
  database: "neo4j"
  cloudProvider: "aws"
  secretName: "aws-credential"
  secretKeyName: "credentials"
consistencyCheck:
  enabled: true