{
 "title": "flaskapp",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Total requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "description": "Cantidad total de peticiones HTTP en la aplicación intermediaria de Flask.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "expr": "flask_http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "description": "HTTP requests de Flask por segundo",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(flask_http_requests_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "max_over_time(flask_http_requests_total[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}