mariadb:
  enabled: true
  architecture: replication
  primary:
    resources:
      limits:
        cpu: "1"
        memory: "4Gi"
  secondary:
    replicaCount: 2
    resources:
      limits:
        cpu: "0.5"
        memory: "2Gi"
  metrics:
    enabled: true
    serviceMonitor: 
      enabled: true
      namespace: monitoring
elasticsearch:
  enabled: true
  elastic:
    version: 8.6.1
    mastercount: 1
    datacount: 1
    name: ic4302
  kibana:
    version: 8.6.1
    replicas: 1
    name: ic4302
elasticprometheus:
  env:
    ES_USERNAME: elastic
  extraEnvSecrets:
    ES_PASSWORD:
      secret: ic4302-es-elastic-user
      key: elastic
  es:
    uri: http://ic4302-es-http:9200
  serviceMonitor:
    enabled: true
    namespace: monitoring
    
mongodb: 
  enabled: false
  auth:
    usernames: ["admin"]
    passwords: ["admin"]
    databases: ["Pokemon"]
  global:
    namespaceOverride: mongodb
  architecture: replicaset
  replicaCount: 3
  resources: 
    limits: 
      cpu: "0.6"
      memory: "2Gi"
  metrics: 
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
postgresql-ha:
  enabled: false
  postgresql:
    database: "pokemon"
  pgpool:
    pgpool:
      maxPool: 25
  persistence:
    enabled: false
    size: "2Gi"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
mariadb-galera:
  enabled: false
  replicaCount: 2
  metrics: 
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
postgresql:
  enabled: false
  primary:
    resources:
      limits:
        cpu: "1"
        memory: "4Gi"
  auth:
    database: "Pokemon"
    username: "admin"
    password: "admin"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
