mariadb:
  enabled: false
  architecture: replication
  primary:
    resources:
      limits:
        cpu: "1"
        memory: "4Gi"
  secondary:
    replicaCount: 2
    resources:
      limits:
        cpu: "0.5"
        memory: "2Gi"
  metrics:
    enabled: true
    serviceMonitor: 
      enabled: true
      namespace: monitoring
elastic:
  enabled: false
  version: 8.6.1
  replicas: 1
  name: ic4302
mongodb: 
  enabled: false
  auth:
    usernames: ["admin"]
    passwords: ["admin"]
    databases: ["Pokemon"]
  global:
    namespaceOverride: mongodb
  architecture: replicaset
  replicaCount: 3
  resources: 
    limits: 
      cpu: "0.6"
      memory: "2Gi"
  metrics: 
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
postgresql-ha:
  enabled: false
  postgresql:
    database: "pokemon"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
mariadb-galera:
  enabled: false
  replicaCount: 2
  metrics: 
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
postgresql:
  enabled: true
  primary:
    resources:
      limits:
        cpu: "1"
        memory: "4Gi"
  auth:
    database: "Pokemon"
    username: "admin"
    password: "admin"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
