config:
  controller:
    replicas: 1
    name: controller
    crawler_queue: "CRAWLER_QUEUE"
    image: dandiego235/controllerbio:2
    interval: 1
  crawler:
    replicas: 1
    name: crawler
    crawler_queue: "CRAWLER_QUEUE"
    spacy_queue: "SPACY_QUEUE"
    image: dandiego235/crawlerbio:2