-- TABLES

CREATE TABLE "ADMIN"."SITEINFOS" 
   (	"SITEINFOID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SITEINFONAME" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP", 
	"SITEINFODBNAME" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP", 
	"SITELANGUAGE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

CREATE INDEX "ADMIN"."IDX_SITEINFODBNAME" ON "ADMIN"."SITEINFOS" ("SITEINFODBNAME") 
   INDEXTYPE IS "CTXSYS"."CONTEXT"  PARAMETERS ('sync (every "sysdate+(10/1440)")');

CREATE INDEX "ADMIN"."IDX_SITELANGUAGE" ON "ADMIN"."SITEINFOS" ("SITELANGUAGE") 
   INDEXTYPE IS "CTXSYS"."CONTEXT"  PARAMETERS ('sync (every "sysdate+(10/1440)")');

CREATE INDEX "ADMIN"."IDX_SITEINFONAME" ON "ADMIN"."SITEINFOS" ("SITEINFONAME") 
   INDEXTYPE IS "CTXSYS"."CONTEXT"  PARAMETERS ('sync (every "sysdate+(10/1440)")');

CREATE UNIQUE INDEX "ADMIN"."SITEINFOS_PK" ON "ADMIN"."SITEINFOS" ("SITEINFOID") 
  ;

CREATE INDEX "ADMIN"."SITENAMES_INDEX" ON "ADMIN"."SITEINFOS" ("SITEINFONAME", "SITEINFODBNAME") 
  ;

ALTER TABLE "ADMIN"."SITEINFOS" MODIFY ("SITEINFOID" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."SITEINFOS" ADD CONSTRAINT "SITEINFOS_PK" PRIMARY KEY ("SITEINFOID")
  USING INDEX  ENABLE;




CREATE TABLE "ADMIN"."PAGES" 
   (	"PAGEID" NUMBER, 
	"PAGETITLE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"PAGENAMESPACE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"PAGEREDIRECT" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"PAGEHASREDIRECT" NUMBER(1,0), 
	"PAGELASTMODIFIED" DATE, 
	"PAGELASTMODIFIEDUSER" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PAGEBYTES" NUMBER, 
	"PAGETEXT" CLOB COLLATE "USING_NLS_COMP", 
	"PAGEWIKIPEDIALINK" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP", 
	"PAGEWIKIPEDIAGENERATED" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP", 
	"PAGENUMBERLINKS" NUMBER, 
	"SITEINFOID" NUMBER, 
	"PAGETITLEKEY" RAW(16), 
	"PAGEPOINTS" NUMBER DEFAULT 0
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

CREATE INDEX "ADMIN"."IDX_PAGELASTMODIFIEDUSER" ON "ADMIN"."PAGES" ("PAGELASTMODIFIEDUSER") 
   INDEXTYPE IS "CTXSYS"."CONTEXT"  PARAMETERS ('sync (every "sysdate+(10/1440)")');

CREATE INDEX "ADMIN"."IDX_PAGEWIKIPEDIALINK" ON "ADMIN"."PAGES" ("PAGEWIKIPEDIALINK") 
   INDEXTYPE IS "CTXSYS"."CONTEXT"  PARAMETERS ('sync (every "sysdate+(10/1440)")');

CREATE INDEX "ADMIN"."IDX_PAGEWIKIPEDIAGENERATED" ON "ADMIN"."PAGES" ("PAGEWIKIPEDIAGENERATED") 
   INDEXTYPE IS "CTXSYS"."CONTEXT"  PARAMETERS ('sync (every "sysdate+(10/1440)")');

CREATE INDEX "ADMIN"."IDX_PAGETEXT" ON "ADMIN"."PAGES" ("PAGETEXT") 
   INDEXTYPE IS "CTXSYS"."CONTEXT"  PARAMETERS ('sync (every "sysdate+(10/1440)")');

CREATE INDEX "ADMIN"."IDX_PAGETITLE" ON "ADMIN"."PAGES" ("PAGETITLE") 
   INDEXTYPE IS "CTXSYS"."CONTEXT"  PARAMETERS ('sync (every "sysdate+(10/1440)")');

CREATE INDEX "ADMIN"."IDX_PAGENAMESPACE" ON "ADMIN"."PAGES" ("PAGENAMESPACE") 
   INDEXTYPE IS "CTXSYS"."CONTEXT"  PARAMETERS ('sync (every "sysdate+(10/1440)")');

CREATE INDEX "ADMIN"."IDX_PAGEREDIRECT" ON "ADMIN"."PAGES" ("PAGEREDIRECT") 
   INDEXTYPE IS "CTXSYS"."CONTEXT"  PARAMETERS ('sync (every "sysdate+(10/1440)")');

CREATE UNIQUE INDEX "ADMIN"."PAGES_PK" ON "ADMIN"."PAGES" ("PAGETITLEKEY") 
  ;

CREATE INDEX "ADMIN"."TITLEINDEX" ON "ADMIN"."PAGES" ("PAGETITLE") 
  ;

ALTER TABLE "ADMIN"."PAGES" ADD CONSTRAINT "BOOLEANHASREDIRECT" CHECK ( pageHasRedirect IN (0, 1)) ENABLE;

ALTER TABLE "ADMIN"."PAGES" ADD CONSTRAINT "PAGES_PK" PRIMARY KEY ("PAGETITLEKEY")
  USING INDEX  ENABLE;

ALTER TABLE "ADMIN"."PAGES" ADD CONSTRAINT "PAGES_SITEINFOS_FK" FOREIGN KEY ("SITEINFOID")
	  REFERENCES "ADMIN"."SITEINFOS" ("SITEINFOID") ENABLE NOVALIDATE;






CREATE TABLE "ADMIN"."PAGELINKS" 
   (	"PAGELINKID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ANCHOR" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"LINK" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PAGETITLEKEY" RAW(16)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

CREATE INDEX "ADMIN"."IDX_PAGELINKANCHOR" ON "ADMIN"."PAGELINKS" ("ANCHOR") 
   INDEXTYPE IS "CTXSYS"."CONTEXT"  PARAMETERS ('sync (every "sysdate+(10/1440)")');

CREATE INDEX "ADMIN"."IDX_PAGELINKLINK" ON "ADMIN"."PAGELINKS" ("LINK") 
   INDEXTYPE IS "CTXSYS"."CONTEXT"  PARAMETERS ('sync (every "sysdate+(10/1440)")');

CREATE INDEX "ADMIN"."PAGELINKS_PAGETITLEKEY_INDEX" ON "ADMIN"."PAGELINKS" ("PAGETITLEKEY") 
  ;

CREATE UNIQUE INDEX "ADMIN"."PAGELINKS_PK" ON "ADMIN"."PAGELINKS" ("PAGELINKID") 
  ;

ALTER TABLE "ADMIN"."PAGELINKS" MODIFY ("PAGELINKID" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."PAGELINKS" ADD CONSTRAINT "PAGELINKS_PK" PRIMARY KEY ("PAGELINKID")
  USING INDEX  ENABLE;







CREATE TABLE "ADMIN"."RESTRICTIONS" 
   (	"RESTRICTIONID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP", 
	"PAGETITLEKEY" RAW(16)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

CREATE INDEX "ADMIN"."IDX_RESTRICTIONNAME" ON "ADMIN"."RESTRICTIONS" ("NAME") 
   INDEXTYPE IS "CTXSYS"."CONTEXT"  PARAMETERS ('sync (every "sysdate+(10/1440)")');

CREATE UNIQUE INDEX "ADMIN"."RESTRICTIONS_PK" ON "ADMIN"."RESTRICTIONS" ("RESTRICTIONID") 
  ;

CREATE INDEX "ADMIN"."RESTRICTIONS_PAGETITLEKEY_INDEX" ON "ADMIN"."RESTRICTIONS" ("PAGETITLEKEY") 
  ;

ALTER TABLE "ADMIN"."RESTRICTIONS" MODIFY ("RESTRICTIONID" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."RESTRICTIONS" ADD CONSTRAINT "RESTRICTIONS_PK" PRIMARY KEY ("RESTRICTIONID")
  USING INDEX  ENABLE;





-- PROCEDURES

CREATE OR REPLACE PROCEDURE createSearchView( p_search_term IN VARCHAR2)
IS
BEGIN
EXECUTE IMMEDIATE 'CREATE MATERIALIZED VIEW SearchView
    BUILD IMMEDIATE
    REFRESH FORCE
    ON DEMAND
    AS
    WITH SearchTerm AS (SELECT ''' || p_search_term || ''' AS Term FROM DUAL),
    LinksAggregate AS(
        SELECT 
            l.PAGETITLEKEY, LISTAGG(l.ANCHOR,  '', '' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY l.ANCHOR) AS LinksList, 
            LISTAGG(l.LINK,  '', '' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY l.LINK) AS LinksLinksList
        FROM 
            PAGELINKS l
        GROUP BY 
            l.PAGETITLEKEY
    ), 
    RestrictionsAggregate AS(
        SELECT 
            r.PAGETITLEKEY, LISTAGG(r.Name, '', '' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY r.Name) AS RestrictionsList
        FROM 
            RESTRICTIONS r
        GROUP BY 
            r.PAGETITLEKEY
    )
    SELECT 
        p.PageId, 
        p.PageTitle, 
        p.PageNamespace, 
        p.PageRedirect, 
        ra.RestrictionsList, 
        p.PageHasRedirect, 
        s.SiteInfoName,
        s.SiteInfoDBName,
        s.SiteLanguage, 
        p.PageLastModified, 
        p.PageLastModifiedUser, 
        p.PageBytes, 
        p.PageText, 
        p.PageWikipediaLink, 
        p.pageWikipediaGenerated, 
        la.LinksList, 
        p.PageNumberLinks,
        p.PagePoints,
        RAWTOHEX(p.PageTitleKey) as PageTitleKey,
        la.LinksLinksList
    FROM Pages p
    INNER JOIN SITEINFOS s ON p.siteinfoid = s.siteinfoid
    CROSS JOIN SearchTerm st  
    LEFT JOIN LinksAggregate la ON p.PAGETITLEKEY = la.PAGETITLEKEY
    LEFT JOIN RestrictionsAggregate ra ON p.PAGETITLEKEY = ra.PAGETITLEKEY
    WHERE 
        CONTAINS(p.PageTitle, ''%'' || st.Term || ''%'') > 0 OR 
        CONTAINS(p.PageNamespace, ''%'' || st.Term || ''%'') > 0 OR 
        CONTAINS(p.PageRedirect, ''%'' || st.Term || ''%'') > 0 OR 
        CONTAINS(s.SiteInfoName, ''%'' || st.Term || ''%'') > 0 OR 
        CONTAINS(s.SiteInfoDBName, ''%'' || st.Term || ''%'') > 0 OR 
        CONTAINS(s.SiteLanguage, ''%'' || st.Term || ''%'') > 0 OR 
        CONTAINS(p.PageLastModifiedUser, ''%'' || st.Term || ''%'') > 0 OR 
        CONTAINS(p.PageWikipediaLink, ''%'' || st.Term || ''%'') > 0 OR 
        CONTAINS(p.pageWikipediaGenerated, ''%'' || st.Term || ''%'') > 0 OR 
        TO_CHAR(la.LinksList) LIKE  ''%'' || st.Term || ''%'' OR 
        TO_CHAR(ra.RestrictionsList) LIKE  ''%'' || st.Term || ''%'' OR 
        TO_CHAR(p.PageId) LIKE ''%'' || st.Term || ''%'' OR 
        TO_CHAR(p.PageHasRedirect) LIKE ''%'' || st.Term || ''%'' OR 
        TO_CHAR(p.PageLastModified) LIKE ''%'' || st.Term || ''%'' OR 
        TO_CHAR(p.PageBytes) LIKE ''%'' || st.Term || ''%'' OR 
        TO_CHAR(p.PageNumberLinks) LIKE ''%'' || st.Term || ''%'' OR  
        CONTAINS(p.PageText, ''%'' || st.Term || ''%'') > 0 AND
        ROWNUM <= 500';
        END;


CREATE OR REPLACE PROCEDURE search_facets(facet_cursor OUT SYS_REFCURSOR) IS
BEGIN
    OPEN facet_cursor FOR
    SELECT 'PageNamespaceFacet' AS facet_type, PageNamespace AS id_, COUNT(*) AS count 
    FROM SearchView 
    WHERE PageNamespace IS NOT NULL
    GROUP BY PageNamespace
    UNION ALL
    SELECT 'PageRestrictionsFacet' , RestrictionsList AS id_, COUNT(*) 
    FROM SearchView 
    WHERE RestrictionsList IS NOT NULL
    GROUP BY RestrictionsList
    UNION ALL
    SELECT 'SiteInfoNameFacet', SiteInfoName AS id_, COUNT(*) 
    FROM SearchView 
    WHERE SiteInfoName IS NOT NULL
    GROUP BY SiteInfoName
    UNION ALL
    SELECT 'SiteInfoDBNameFacet' , SiteInfoDBName AS id_, COUNT(*) 
    FROM SearchView 
    WHERE SiteInfoDBName IS NOT NULL
    GROUP BY SiteInfoDBName
    UNION ALL
    SELECT 'SiteLanguageFacet'  , SiteLanguage AS id_, COUNT(*) 
    FROM SearchView 
    WHERE SiteLanguage IS NOT NULL
    GROUP BY SiteLanguage
    UNION ALL
    SELECT 'PageLastModifiedUserFacet', PageLastModifiedUser AS id_, COUNT(*) 
    FROM SearchView 
    WHERE PageLastModifiedUser IS NOT NULL
    GROUP BY PageLastModifiedUser
    UNION ALL
    SELECT 'PageLastModifiedFacet' AS facet_type, TO_CHAR(EXTRACT(YEAR FROM PageLastModified))  AS id_, COUNT(*) AS count 
    FROM SearchView 
    WHERE PageLastModified IS NOT NULL
    GROUP BY EXTRACT(YEAR FROM PageLastModified)
    UNION ALL
    SELECT 'PageHasRedirectFacet' AS facet_type, TO_CHAR(PageHasRedirect) AS id_, COUNT(*) AS count 
    FROM SearchView 
    WHERE PageHasRedirect IS NOT NULL
    GROUP BY PageHasRedirect
    UNION ALL
    SELECT 
    'PageBytesFacet' AS facet_type,
        CASE 
            WHEN PageBytes = 0 THEN '0'
            WHEN PageBytes BETWEEN 1 AND 30000 THEN '1-30000'
            WHEN PageBytes BETWEEN 30001 AND 60000 THEN '30001-60000'
            WHEN PageBytes BETWEEN 60001 AND 90000 THEN '60001-90000'
            WHEN PageBytes BETWEEN 90001 AND 120000 THEN '90001-120000'
            WHEN PageBytes BETWEEN 120001 AND 150000 THEN '120001-150000'
            WHEN PageBytes BETWEEN 150001 AND 180000 THEN '150001-180000'
            WHEN PageBytes BETWEEN 180001 AND 210000 THEN '180001-210000'
            WHEN PageBytes BETWEEN 210001 AND 240000 THEN '210001-240000'
            WHEN PageBytes BETWEEN 240001 AND 270000 THEN '240001-270000'
            ELSE '+300000'
        END AS id_,
        COUNT(*) AS count 
    FROM SearchView 
    WHERE PageBytes IS NOT NULL
    GROUP BY 
        CASE 
            WHEN PageBytes = 0 THEN '0'
            WHEN PageBytes BETWEEN 1 AND 30000 THEN '1-30000'
            WHEN PageBytes BETWEEN 30001 AND 60000 THEN '30001-60000'
            WHEN PageBytes BETWEEN 60001 AND 90000 THEN '60001-90000'
            WHEN PageBytes BETWEEN 90001 AND 120000 THEN '90001-120000'
            WHEN PageBytes BETWEEN 120001 AND 150000 THEN '120001-150000'
            WHEN PageBytes BETWEEN 150001 AND 180000 THEN '150001-180000'
            WHEN PageBytes BETWEEN 180001 AND 210000 THEN '180001-210000'
            WHEN PageBytes BETWEEN 210001 AND 240000 THEN '210001-240000'
            WHEN PageBytes BETWEEN 240001 AND 270000 THEN '240001-270000'
            ELSE '+300000'
        END
    UNION ALL
    SELECT 
    'PageNumberLinksFacet' AS facet_type,
        CASE 
            WHEN PageNumberLinks = 0 THEN '0'
            WHEN PageNumberLinks BETWEEN 1 AND 5 THEN '1-5'
            WHEN PageNumberLinks BETWEEN 6 AND 10 THEN '6-10'
            WHEN PageNumberLinks BETWEEN 11 AND 15 THEN '11-15'
            WHEN PageNumberLinks BETWEEN 16 AND 20 THEN '16-20'
            WHEN PageNumberLinks BETWEEN 21 AND 25 THEN '21-25'
            WHEN PageNumberLinks BETWEEN 26 AND 30 THEN '26-30'
            WHEN PageNumberLinks BETWEEN 31 AND 35 THEN '31-35'
            WHEN PageNumberLinks BETWEEN 36 AND 40 THEN '36-40'
            WHEN PageNumberLinks BETWEEN 41 AND 45 THEN '41-45'
            ELSE '+50'
        END AS id_,
        COUNT(*) AS count 
    FROM SearchView 
    WHERE PageNumberLinks IS NOT NULL
    GROUP BY 
        CASE 
            WHEN PageNumberLinks = 0 THEN '0'
            WHEN PageNumberLinks BETWEEN 1 AND 5 THEN '1-5'
            WHEN PageNumberLinks BETWEEN 6 AND 10 THEN '6-10'
            WHEN PageNumberLinks BETWEEN 11 AND 15 THEN '11-15'
            WHEN PageNumberLinks BETWEEN 16 AND 20 THEN '16-20'
            WHEN PageNumberLinks BETWEEN 21 AND 25 THEN '21-25'
            WHEN PageNumberLinks BETWEEN 26 AND 30 THEN '26-30'
            WHEN PageNumberLinks BETWEEN 31 AND 35 THEN '31-35'
            WHEN PageNumberLinks BETWEEN 36 AND 40 THEN '36-40'
            WHEN PageNumberLinks BETWEEN 41 AND 45 THEN '41-45'
            ELSE '+50'
        END;
END search_facets;

CREATE OR REPLACE PROCEDURE searchWithFacets(
    p_PageLastModifiedUser    IN VARCHAR2 DEFAULT NULL,
    p_PageNamespace           IN VARCHAR2 DEFAULT NULL,
    p_SiteInfoName            IN VARCHAR2 DEFAULT NULL,
    p_SiteInfoDBName          IN VARCHAR2 DEFAULT NULL,
    p_SiteLanguage            IN VARCHAR2 DEFAULT NULL,
    p_pageRestrictions        IN VARCHAR2 DEFAULT NULL,
    p_PageBytesMin            IN VARCHAR2 DEFAULT NULL,
    p_PageBytesMax            IN VARCHAR2 DEFAULT NULL,
    p_pageNumberLinksMin      IN VARCHAR2 DEFAULT NULL,
    p_pageNumberLinksMax      IN VARCHAR2 DEFAULT NULL,
    p_PageLastModified        IN VARCHAR2 DEFAULT NULL,
    p_PageHasRedirect         IN VARCHAR2 DEFAULT NULL,
    main_cursor               OUT SYS_REFCURSOR
) IS
BEGIN
    OPEN main_cursor FOR
    SELECT * 
    FROM SearchView sv
    WHERE 
    (p_PageLastModifiedUser IS NULL OR sv.PageLastModifiedUser LIKE '%' || p_PageLastModifiedUser || '%')
    AND (p_PageNamespace IS NULL OR sv.PageNamespace LIKE '%' || p_PageNamespace || '%')
    AND (p_SiteInfoName IS NULL OR sv.SiteInfoName LIKE '%' || p_SiteInfoName || '%')
    AND (p_SiteInfoDBName IS NULL OR sv.SiteInfoDBName LIKE '%' || p_SiteInfoDBName || '%')
    AND (p_SiteLanguage IS NULL OR sv.SiteLanguage LIKE '%' || p_SiteLanguage || '%')
    AND (p_pageRestrictions IS NULL OR sv.RestrictionsList LIKE '%' || p_pageRestrictions || '%')
    AND ((p_PageBytesMin IS NULL OR p_PageBytesMax IS NULL) OR (sv.PageBytes BETWEEN TO_NUMBER(p_PageBytesMin) AND TO_NUMBER(p_PageBytesMax)))
    AND ((p_pageNumberLinksMin IS NULL OR p_pageNumberLinksMax IS NULL) OR (sv.PAGENUMBERLINKS BETWEEN TO_NUMBER(p_pageNumberLinksMin) AND TO_NUMBER(p_pageNumberLinksMax)))
    AND (p_PageLastModified IS NULL OR TO_CHAR(EXTRACT(YEAR FROM sv.PageLastModified)) = p_PageLastModified)
    AND (p_PageHasRedirect IS NULL OR sv.PageHasRedirect LIKE '%' || p_PageHasRedirect || '%');
END searchWithFacets;


CREATE OR REPLACE PROCEDURE update_pagepoints(p_PageTitleKey VARCHAR2, p_Value NUMBER) IS
BEGIN
    UPDATE Pages
    SET PagePoints = PagePoints + p_Value
    WHERE PAGETITLEKEY = p_PageTitleKey;
    COMMIT;
END update_pagepoints;
