mongo:
  enabled: true
  config:
    namespace: default
    connectionString: databases-mongodb.default.svc.cluster.local:27017
    bucketName: tec-ic4302-02-2023
    path: 2019073558/mongodb
    maxBackups: 3
    secret: databases-mongodb
    name:  "202310202250"
    schedule: "0 */12 * * *"
    diskSize: 1
    storageClass: hostpath
    provider: aws
    type: restore
postgresql:
  enabled: false
  config:
    namespace: default
    host: databases-postgresql.default.svc.cluster.local
    db: "Pokemon"
    user: "admin"
    password: "admin"
    port: "5432"
    bucketName: tec-ic4302-02-2023
    path: 2019073558/postgresql
    maxBackups: 3
    name: Pokemon-202310181455.sql 
    schedule: "0 */12 * * *"
    diskSize: 2
    storageClass: hostpath
    provider: aws
    type: restore