mongo:
  enabled: false
  config:
    namespace: default
    connectionString: databases-mongodb.default.svc.cluster.local:27017
    bucketName: tec-ic4302-02-2023
    path: 2019073558/mongodb
    maxBackups: 3
    secret: databases-mongodb
    name:  "202310202250"
    schedule: "0 */12 * * *"
    diskSize: 1
    storageClass: hostpath
    provider: aws
    type: restore
maria:
  enabled: false
  config:
    namespace: default
    connectionString: databases-mariadb
    bucketName: tec-ic4302-02-2023
    path: 2019073558/mariadb
    maxBackups: 3
    secret: databases-mariadb
    name:  pokemon_db-202310210452.sql
    schedule: "0 */12 * * *"
    diskSize: 1
    storageClass: hostpath
    provider: aws
    type: restore
postgresql:
  enabled: true
  config:
    namespace: default
    host: databases-postgresql.default.svc.cluster.local
    db: "Pokemon"
    user: "admin"
    password: "admin"
    port: "5432"
    bucketName: tec-ic4302-02-2023
    path: 2019073558/postgresql
    maxBackups: 3
    name: Pokemon-202310212135.sql
    schedule: "0 */12 * * *"
    diskSize: 2
    storageClass: hostpath
    provider: aws
    type: restore
couchdb:
  enabled: false
  config:
    namespace: default
    host: databases-couchdb.default.svc.cluster.local
    db: "pokemon"
    user: "admin"
    password: "admin"
    port: "5984"
    bucketName: tec-ic4302-02-2023
    path: 2019073558/couchdb
    maxBackups: 3
    name: couchdb-202310230113.json 
    schedule: "0 */12 * * *"
    diskSize: 1
    storageClass: hostpath
    provider: aws
    type: restore
    