mongodb:
  enabled: true
  auth:
    usernames: ["admin"]
    passwords: ["admin"]
    databases: ["Pokemon"]
  global:
    namespaceOverride: mongodb
  architecture: replicaset
  replicaCount: 1
  resources: 
    limits: 
      cpu: "0.6"
      memory: "2Gi"

elasticsearch:
  enabled: true
  elastic:
    version: 8.6.1
    replicas: 1
    name: ic4302
  kibana:
    version: 8.6.1
    replicas: 1
    name: ic4302
  
postgresql:
  enabled: true
  image:
    tag: 14.9.0
  primary:
    resources:
      limits:
        cpu: "1"
        memory: "4Gi"
  auth:
    database: "Pokemon"
    username: "admin"
    password: "admin"

mariadb:
  enabled: true
  auth:
    rootPassword: "1234"
  resources:
    limits:
      cpu: "0.5"
      memory: "2Gi"

neo4j:
  enabled: true

couchdb:
  enabled: true