mongodb:
  enabled: false
mariadb:
  enabled: true
elasticsearch:
  enabled: true
  elastic:
    version: 8.6.1
    replicas: 1
    name: ic4302
  kibana:
    version: 8.6.1
    replicas: 1
    name: ic4302
postgresql:
  enabled: false
  image:
    tag: 14.9.0
  primary:
    resources:
      limits:
        cpu: "1"
        memory: "4Gi"
  auth:
    database: "Pokemon"
    username: "admin"
    password: "admin"
neo4j:
  enabled: false
couchdb:
  enabled: false
  clusterSize: 1
  adminUsername: "admin"
  adminPassword: "admin"
  image:
    tag: 3.3.2
  couchdbConfig:
    couchdb:
      uuid: $(shell curl -s https://www.uuidgenerator.net/api/version4 2>/dev/null | tr -d -)