mongodb:
  enabled: false
mariadb:
  enabled: false
elasticsearch:
  enabled: false
  elastic:
    version: 8.6.1
    replicas: 1
    name: ic4302
  kibana:
    version: 8.6.1
    replicas: 1
    name: ic4302
postgresql:
  enabled: false
  image:
    tag: 14.9.0
  primary:
    resources:
      limits:
        cpu: "1"
        memory: "4Gi"
  auth:
    database: "Pokemon"
    username: "admin"
    password: "admin"
couchdb:
  enabled: false
  clusterSize: 1
  resources:
    limits:
      cpu: "1"
      memory: "4Gi"
  couchdbConfig:
    couchdb:
      uuid: $(shell curl -s https://www.uuidgenerator.net/api/version4 2>/dev/null | tr -d -)
neo4j:
  enabled: true
  neo4j:
    name: my-standalone
    resources:
      cpu: "0.5"
      memory: "2Gi"
    password: "neo4j-password"
    edition: "enterprise"
    acceptLicenseAgreement: "yes"
  config:
    server.directories.plugins: "/var/lib/neo4j/labs"
    dbms.security.procedures.unrestricted: "apoc.export.*,apoc.import.*,apoc.*,apoc.export"
    server.config.strict_validation.enabled: "false"
    dbms.security.procedures.allowlist: "apoc.export.*,apoc.import.*"
  apoc_config:
    apoc.trigger.enabled: "true"
    apoc.jdbc.neo4j.url: "jdbc:foo:bar"
    apoc.import.file.enabled: "true"
    apoc.export.file.enabled: "true"
  env:
    NEO4J_PLUGINS: '["apoc"]'
  volumes:
    data:
      mode: defaultStorageClass
      defaultStorageClass:
        requests:
          storage: 2Gi