config:
  flaskmariadb:
    enabled: true
    replicas: 1
    name: flaskmariadb
    image: dado715/flask-mariadb:latest
  postgresql:
    enabled: false
    name: postgreflask
    image: dandiego235/postgreflask
    database: "Pokemon"
    user: "admin"
    password: "admin"
    service: "databases-postgresql"
  mongodb:
    enabled: true
    name: mongodb
    image: dandiego2356/mongoflask
    database: "Pokemon"
    user: "admin"
    password: "admin"
    service: "databases-mongodb-headless"
  flaskmariadbgal:
    enabled: false
    replicas: 1
    name: flaskmariadbgal
    image: dado715/flask-mariadb:latest