{{- if .Values.elasticsearch.enabled }}
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Values.elasticsearch.kibana.name }}
spec:
  version: {{ .Values.elasticsearch.kibana.version }}
  count: {{ .Values.elasticsearch.kibana.replicas }}
  elasticsearchRef:
    name: {{ .Values.elasticsearch.kibana.name }}
{{- end }}